version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/zcong1993/gist

    steps:
      - checkout

      - run:
          name: get deps
          command: |
            go get -t -d -v ./...
            go get -v github.com/mitchellh/gox

      - run:
          name: build
          command: |
            chmod +x ./build.sh
            make build
