version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/your github username/your project name

    steps:
      - checkout

      - run:
          name: get deps
          command: go get -t -d -v ./...

      - run:
          name: build
          command: go build -v ./...

